add https

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,11 +20,24 @@ jobs:
         AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
         SOURCE_DIR: 'dist'      # optional: defaults to entire repository
 
+    - name: get updated files
+      run: |
+        # allow grep to fail
+        set +e
+        FILES=$(git log --stat="1000" -1 | grep '|' | awk '{print "/"$1}' | grep -e '\.html$')
+        set -e
+        [ -z "$FILES" ] && touch .updated_files && exit 0
+        for file in $FILES; do
+          echo $file
+          # add bare directory to list of updated paths when we see index.html
+          [[ "$file" == *"/index.html" ]] && echo $file | sed -e 's/\/index.html$/\//'
+        done | sort | uniq | tr '\n' ' ' > .updated_files
+
     # Invalidate Cloudfront (this action)
     - name: invalidate
       uses: chetan/invalidate-cloudfront-action@v2
       env:
-        PATHS: '/index.html'
+        PATHS_FROM: .updated_files
         DISTRIBUTION: 'E3CI14IK010OSG'
         AWS_REGION: 'us-east-1'
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
